-- Insert Meetups
INSERT INTO MEETUP (ID, EVENT, DATE, REGISTERED)
VALUES (1, 'JAVA', '21/09/2021',TRUE);

INSERT INTO MEETUP (ID, EVENT, DATE, REGISTERED)
VALUES (2, 'PYTHON', '21/09/2021',TRUE);

INSERT INTO MEETUP (ID, EVENT, DATE, REGISTERED)
VALUES (3, 'C#', '21/09/2021',TRUE);

INSERT INTO MEETUP (ID, EVENT, DATE, REGISTERED)
VALUES (4, 'C++', '21/09/2021',TRUE);


-- Insert Registration
INSERT INTO REGISTRATION (ID, PERSON_NAME, DATE_OF_REGISTRATION,  CODE, ID_MEETUP)
VALUES (10, 'KAMILA','10/02/2022', '001', 1);

INSERT INTO REGISTRATION (ID, PERSON_NAME, DATE_OF_REGISTRATION,  CODE, ID_MEETUP)
VALUES (14, 'KARINE','10/02/2022', '005', 2);

INSERT INTO REGISTRATION (ID, PERSON_NAME, DATE_OF_REGISTRATION,  CODE, ID_MEETUP)
VALUES (11, 'ADLER','10/02/2022', '002', 2);

INSERT INTO REGISTRATION (ID, PERSON_NAME, DATE_OF_REGISTRATION,  CODE)
VALUES (12, 'MARIA','10/02/2022', '003');

INSERT INTO REGISTRATION (ID, PERSON_NAME, DATE_OF_REGISTRATION,  CODE, ID_MEETUP)
VALUES (13, 'JOSE','10/02/2022', '004', 1);


-- Selects
SELECT * FROM MEETUP;
SELECT * FROM REGISTRATION

-- Selects de todas as pessoas registratadas nos meetups
SELECT M.EVENT, M.DATE, R.PERSON_NAME, R.DATE_OF_REGISTRATION, R.CODE FROM MEETUP AS M
INNER JOIN REGISTRATION AS R ON M.ID = R.ID_MEETUP
WHERE ID_MEETUP IN(1,2);

SELECT M.EVENT, M.DATE, R.PERSON_NAME, R.DATE_OF_REGISTRATION, R.CODE FROM MEETUP AS M
INNER JOIN REGISTRATION AS R ON M.ID = R.ID_MEETUP
WHERE ID_MEETUP IN(1,2);

